kind: pipeline
type: docker
name: hugo

steps:
- name: build
  image: golang
  commands:
  - go get -v  github.com/gohugoio/hugo
  - git clone https://github.com/olOwOlo/hugo-theme-even themes/even
  - hugo 
- name: publish
  image: plugins/gh-pages
  settings:
    ssh_key:
      from_secret: github_ssh_key
    pages_directory: public/
    target_branch: master
      