kind: pipeline
type: docker
name: hugo

steps:
- name: build
  image: dotopt/hugo
  commands:
  - git clone https://github.com/olOwOlo/hugo-theme-even themes/even
  - hugo 
- name: publish
  image: plugins/gh-pages
  settings:
    username: 
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: public/
    target_branch: master
      